# Build file for binary write/read code
#
# To build the debug version, simply type 'scons dbg' on the commandline. This will produce
# executables named 'writebin','readbin' in the dbg directory
# 
#
#


Import('env')

# build object files
writebin = env.Object(['writebin.c'])
readbin = env.Object(['readbin.c'])
aiowrite = env.Object(['aiowrite.c'])
simple_nc4wr = env.Object(['simple_nc4_wr.c'])
#            CPPPATH = '/usr/include/hdf')
#obj_list = env.Object(Split('main.c get_sstfiles.c jdn_l.c read_landmask.c write_sst.c dateutil.c'))

# link program from object files
env.Program('writebin', writebin)
env.Program('readbin', readbin)
env.Program('aiowrite', aiowrite,
            LIBS = ['aio'])
env.Program('simple_nc4_write', simple_nc4wr,
            LIBS = ['netcdf'])
#            LIBPATH = ['/usr/lib/hdf4', '/usr/local/cuda/lib64'])
#env.Program('pgapfill', obj_list + hdf_list + persist,
#            LIBS = ['jpeg', 'z', 'mfhdf', 'df', 'cudart'],
#            LIBPATH = ['/usr/lib/hdf4', '/usr/local/cuda/lib64'])

